//! Plugin-local error type.
//!
//! The SDK's `PluginError` is generated by `wit-bindgen` and therefore only
//! exists on `wasm32`. To keep the core logic unit-testable with plain
//! `cargo test` on the host target we use this native mirror and convert at the
//! `wasm32`-only boundary in `lib.rs`.

use core::fmt;

/// Everything that can go wrong, mapped 1:1 onto `entangle:plugin/types.plugin-error`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Error {
    /// The caller handed us bytes we cannot act on. Never a bug in the plugin.
    InvalidInput(String),
    /// The request is well-formed but exceeds a safety budget.
    ResourceExhausted(String),
    /// A codec failed in a way that is not attributable to the input shape.
    Internal(String),
}

impl fmt::Display for Error {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Error::InvalidInput(m) => write!(f, "invalid input: {m}"),
            Error::ResourceExhausted(m) => write!(f, "resource exhausted: {m}"),
            Error::Internal(m) => write!(f, "internal error: {m}"),
        }
    }
}

impl std::error::Error for Error {}

/// Convenience alias.
pub type Result<T> = core::result::Result<T, Error>;
