//! [`LoadedPlugin`] — a compiled + ready-to-instantiate WebAssembly component.

use crate::{engine::HostEngine, errors::HostError, state::HostState};
use entangle_types::{plugin_id::PluginId, tier::Tier};
use wasmtime::component::{Component, Linker};
use wasmtime::Store;

/// A WebAssembly component that has been compiled and is ready to instantiate.
///
/// Compilation is the expensive step (validates + compiles wasm to native);
/// it is performed once in [`LoadedPlugin::from_bytes`] and can then be
/// instantiated multiple times via [`LoadedPlugin::run_one_shot`].
pub struct LoadedPlugin {
    component: Component,
    plugin_id: PluginId,
    effective_tier: Tier,
}

/// The outcome of a single plugin invocation.
///
/// # Phase-1.0 stub
/// In this iteration (iter 6) `output` is always empty because we do not yet
/// invoke any exported function — that requires bindgen which is iter 9-12.
/// Instantiation is verified, the epoch timeout is wired, and log lines
/// accumulated in [`HostState::log_buffer`] are returned.
#[derive(Debug, Clone)]
pub struct PluginRunResult {
    /// Raw bytes returned by the plugin's export (empty in iter-6 stub).
    pub output: Vec<u8>,
    /// Log lines emitted by the plugin via the `entangle:plugin/logging` stub.
    ///
    /// Each entry is `(level, message)`.
    pub log_lines: Vec<(String, String)>,
}

impl LoadedPlugin {
    /// Compile a WebAssembly component from raw bytes.
    ///
    /// This validates the component and compiles it to native code using the
    /// provided [`HostEngine`]. Returns [`HostError::Compile`] if the bytes are
    /// not a valid component.
    pub fn from_bytes(
        engine: &HostEngine,
        bytes: &[u8],
        plugin_id: PluginId,
        effective_tier: Tier,
    ) -> Result<Self, HostError> {
        let component = Component::from_binary(engine.engine(), bytes)?;
        Ok(Self {
            component,
            plugin_id,
            effective_tier,
        })
    }

    /// Instantiate the component and run a single invocation.
    ///
    /// # Timeout
    /// An epoch-based timeout is enforced: a tokio task increments the engine
    /// epoch after `timeout_ms` milliseconds. The store's epoch deadline is set
    /// to 1, so any async yield point after the deadline causes a trap.
    ///
    /// # Phase-1.0 stub — no export invocation
    /// In iter 6 we verify that the component *instantiates* cleanly but do not
    /// call any exported function. Calling exports requires `bindgen!`-generated
    /// bindings which are introduced in iter 9-12 once we have a real plugin.
    ///
    /// The `input` parameter is accepted for API compatibility but is unused
    /// until iter 9.
    pub async fn run_one_shot(
        &self,
        engine: &HostEngine,
        _input: &[u8],
        timeout_ms: u64,
    ) -> Result<PluginRunResult, HostError> {
        let mut store = Store::new(
            engine.engine(),
            HostState::new(self.plugin_id.clone(), self.effective_tier),
        );

        // Epoch-based timeout: a background task bumps the epoch once the
        // deadline expires. The store deadline is 1, so any async yield after
        // the timer fires causes the wasm execution to trap.
        let engine_for_timer = engine.engine().clone();
        let timer_handle = tokio::spawn(async move {
            tokio::time::sleep(std::time::Duration::from_millis(timeout_ms)).await;
            engine_for_timer.increment_epoch();
        });
        store.set_epoch_deadline(1);

        // Wire up WASI 0.2 (p2) host implementations.
        // The linker is local to this invocation; in future iterations the
        // broker will provide a pre-built linker with capability stubs installed.
        let mut linker = Linker::<HostState>::new(engine.engine());
        wasmtime_wasi::p2::add_to_linker_async(&mut linker)
            .map_err(|e| HostError::LinkerSetup(e.into()))?;

        // Logging stub registration note:
        // The `entangle:plugin/logging@0.1.0` interface would normally be
        // registered here via `linker.instance("entangle:plugin/logging@0.1.0")
        // .func_wrap(...)`. In iter 6 we skip this because:
        // (a) the WIT package in entangle-wit is still a placeholder with no
        //     real interface definitions, and
        // (b) raw Linker::func_wrap for component-model requires knowing the
        //     canonical ABI type layout, which is generated by bindgen! (iter 9).
        // Capability fetch and other entangle-wit imports likewise return
        // `not-granted` by default — the broker replaces these in iter 7-9.
        // TODO(iter-9): replace this comment with bindgen!-backed linker setup.

        // Instantiate — this is the primary verification in iter 6.
        let _instance = linker
            .instantiate_async(&mut store, &self.component)
            .await
            .map_err(|e| HostError::Instantiate(e.into()))?;

        // Phase-1.0 stub: we do not invoke any exported function here.
        // Invoking exports (e.g. the `run` export) requires bindgen!-generated
        // typed wrappers; that is introduced in iter 9-12.
        // TODO(iter-9): invoke the `run` export and populate `output`.

        timer_handle.abort();

        let log_lines = std::mem::take(&mut store.data_mut().log_buffer);
        Ok(PluginRunResult {
            output: Vec::new(),
            log_lines,
        })
    }

    /// Returns the plugin identifier.
    pub fn plugin_id(&self) -> &PluginId {
        &self.plugin_id
    }

    /// Returns the effective capability tier for this plugin.
    pub fn effective_tier(&self) -> Tier {
        self.effective_tier
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::engine::HostEngine;
    use entangle_types::{plugin_id::PluginId, tier::Tier};

    fn test_plugin_id() -> PluginId {
        "aabbccddeeff00112233445566778899/test-plugin@0.1.0"
            .parse()
            .unwrap()
    }

    /// Test 1: engine creation succeeds with component-model + async config.
    #[test]
    fn engine_creates_ok() {
        assert!(HostEngine::new().is_ok());
    }

    /// Test 2: passing invalid bytes returns HostError::Compile.
    #[test]
    fn compile_invalid_bytes_errors() {
        let engine = HostEngine::new().unwrap();
        let result = LoadedPlugin::from_bytes(&engine, &[0, 0, 0, 0], test_plugin_id(), Tier::Pure);
        assert!(
            matches!(result, Err(HostError::Compile(_))),
            "expected Compile error, got: {:?}",
            result.err()
        );
    }

    /// Test 3: a minimal component with no imports and no exports instantiates
    /// cleanly. The component text uses the WAT component-model syntax supported
    /// by the `wat` crate (wast 0.248 includes component-model support).
    ///
    /// If the `wat` crate in use does not support the component text format,
    /// this test is marked `#[ignore]` with a TODO referencing iter 9.
    ///
    /// We use a truly empty component `(component)` which is valid component-
    /// model binary and requires no imports, making it safe to instantiate
    /// even though we have WASI host functions registered.
    #[tokio::test]
    async fn instantiate_minimal_component_succeeds() {
        // A minimal component with no imports and no exports.
        // WASI host functions are registered in the linker but the component
        // never references them, so instantiation succeeds without satisfying
        // any import.
        let component_wat = r#"(component)"#;

        let engine = HostEngine::new().unwrap();

        let bytes = match wat::parse_str(component_wat) {
            Ok(b) => b,
            Err(e) => {
                // If the wat crate does not support component text format,
                // skip rather than fail — this will be resolved in iter 9
                // when bindgen! and proper component fixtures are introduced.
                // TODO(iter-9): replace with a real component fixture.
                eprintln!("wat::parse_str does not support component format: {e}; skipping test");
                return;
            }
        };

        let plugin =
            LoadedPlugin::from_bytes(&engine, &bytes, test_plugin_id(), Tier::Pure).unwrap();

        let result = plugin.run_one_shot(&engine, &[], 5_000).await;
        assert!(result.is_ok(), "instantiation failed: {:?}", result.err());
        let run_result = result.unwrap();
        // Phase-1.0 stub: output is always empty (no export invocation yet).
        assert!(run_result.output.is_empty());
    }
}
