# Homebrew formula for Entanglement (`entangle` CLI + `entangled` daemon).
#
# ─────────────────────────────────────────────────────────────────────────────
# THIS FORMULA IS A TEMPLATE. It will NOT install until the placeholders below
# are replaced with values from a real tagged release. `brew install` fails
# loudly on the placeholder sha256 strings — that is deliberate: a formula that
# silently installs an unverified bottle is worse than one that refuses.
#
# What the release job (or a human cutting a release) must fill in:
#
#   1. `version "PLACEHOLDER_VERSION"`
#      → the release version WITHOUT the leading "v", e.g. "0.1.0".
#        The `url`s below interpolate it back into the tag as "v#{version}",
#        matching .github/workflows/release.yml, which names every asset
#        `entanglement-<tag>-<rust-target>.tar.gz` with the tag's "v" included.
#
#   2. The four `sha256` lines
#      → the first field of the matching `.sha256` asset published next to each
#        tarball on the release page:
#
#        PLACEHOLDER_SHA256_DARWIN_ARM64 ← entanglement-vX.Y.Z-aarch64-apple-darwin.tar.gz.sha256
#        PLACEHOLDER_SHA256_DARWIN_X8664 ← entanglement-vX.Y.Z-x86_64-apple-darwin.tar.gz.sha256
#        PLACEHOLDER_SHA256_LINUX_ARM64  ← entanglement-vX.Y.Z-aarch64-unknown-linux-gnu.tar.gz.sha256
#        PLACEHOLDER_SHA256_LINUX_X8664  ← entanglement-vX.Y.Z-x86_64-unknown-linux-gnu.tar.gz.sha256
#
#        e.g. `sha256 "$(cut -d" " -f1 entanglement-v0.1.0-aarch64-apple-darwin.tar.gz.sha256)"`
#
# Nothing else needs to change between releases. Once filled in, the file is
# copied to the tap repository (homebrew-entanglement) as Formula/entangle.rb,
# which makes `brew install thekozugroup/entanglement/entangle` work.
#
# Verify before publishing:  brew audit --strict --online entangle
#                            brew install --build-from-source ./entangle.rb
#                            brew test entangle
# ─────────────────────────────────────────────────────────────────────────────
class Entangle < Formula
  desc "Runtime that turns the devices you own into one cooperative compute fabric"
  homepage "https://github.com/thekozugroup/Entanglement"
  version "PLACEHOLDER_VERSION"
  license "Apache-2.0"

  # Prebuilt, cosign-signed tarballs straight from the GitHub release — the
  # same artifacts scripts/install.sh downloads. No build dependency on Rust.
  on_macos do
    on_arm do
      url "https://github.com/thekozugroup/Entanglement/releases/download/v#{version}/entanglement-v#{version}-aarch64-apple-darwin.tar.gz"
      sha256 "PLACEHOLDER_SHA256_DARWIN_ARM64"
    end
    on_intel do
      url "https://github.com/thekozugroup/Entanglement/releases/download/v#{version}/entanglement-v#{version}-x86_64-apple-darwin.tar.gz"
      sha256 "PLACEHOLDER_SHA256_DARWIN_X8664"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/thekozugroup/Entanglement/releases/download/v#{version}/entanglement-v#{version}-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "PLACEHOLDER_SHA256_LINUX_ARM64"
    end
    on_intel do
      url "https://github.com/thekozugroup/Entanglement/releases/download/v#{version}/entanglement-v#{version}-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "PLACEHOLDER_SHA256_LINUX_X8664"
    end
  end

  def install
    # The release tarball unpacks to a single top-level directory
    # (entanglement-<tag>-<target>/) holding both binaries plus docs; Homebrew
    # has already chdir'd into it by the time `install` runs.
    bin.install "entangled", "entangle"
    doc.install "README.md" if File.exist?("README.md")
    doc.install "architecture.md" if File.exist?("architecture.md")
    doc.install "tutorial.md" if File.exist?("tutorial.md")

    # Shell completions are generated by the CLI itself (`entangle completions
    # <shell>`), so they always match the installed binary.
    generate_completions_from_executable(bin/"entangle", "completions", shell_parameter_format: :arg)
  end

  def caveats
    <<~EOS
      Before starting the daemon, create an identity and config:

        entangle init            # writes ~/.entangle/{identity.key,config.toml,keyring.toml,peers.toml}

      Then either run it in the foreground:

        entangled run

      or start it as a background service:

        brew services start entangle

      The daemon resolves everything (config, keyring, identity, and its
      Unix socket) from $HOME/.entangle — there is no config-dir flag — so the
      service intentionally runs as your user with your normal $HOME. That
      keeps `entangle` and `entangled` pointed at the same state directory.

      Health check:  entangle doctor
    EOS
  end

  service do
    run [opt_bin/"entangled", "run"]
    keep_alive true
    # Deliberately NOT overriding HOME: the daemon reads $HOME/.entangle
    # (crates/entangle-bin/src/config.rs), and `entangle init` writes there,
    # so the CLI and daemon must agree on the same home directory.
    working_dir Dir.home
    log_path var/"log/entangled.log"
    error_log_path var/"log/entangled.log"
  end

  test do
    ENV["HOME"] = testpath

    assert_match "entangle #{version}", shell_output("#{bin}/entangle --version")
    assert_match "entangled #{version}", shell_output("#{bin}/entangled --version")

    # `init --non-interactive` takes every default (transports=local,
    # max_tier=5, generate a fresh identity) and must leave a usable ~/.entangle.
    system bin/"entangle", "init", "--non-interactive"
    assert_predicate testpath/".entangle/config.toml", :exist?
    assert_predicate testpath/".entangle/identity.key", :exist?
    assert_match "transports = [\"local\"]", (testpath/".entangle/config.toml").read

    # doctor exits 0 even with the daemon down (unreachability is a warning).
    assert_match "identity", shell_output("#{bin}/entangle doctor")

    # With no daemon running, `entangled status` must fail — this is exactly
    # what the container HEALTHCHECK relies on.
    shell_output("#{bin}/entangled status 2>&1", 1)

    # Completions are generated from the real command tree.
    assert_match "_entangle", shell_output("#{bin}/entangle completions bash")
  end
end
